// =============================================================================
//  baas/openapi/openapi.h  —  the API, described, from the table that serves it
// =============================================================================
//  An OpenAPI 3.0 document for everything under `/v1` (plus the three routes that
//  are deliberately outside it: `/healthz`, `/metrics`, `/dashboard`).
//
//  THE POINT IS THAT IT CANNOT DRIFT. A hand-written spec beside a hand-written
//  router is two tables that agree on the day they are written and never again —
//  this project has watched that happen to an attribution ledger (chapter 131) and
//  to a Postgres deploy path that was a sentence for eleven slices (chapter 141).
//  So `test_baas_openapi` asks Drogon for the routes it ACTUALLY registered
//  (`getHandlersInfo()`) and compares that set to `spec()`, both directions:
//
//    * a route added without a spec entry  -> RED
//    * a spec entry for a route that is gone -> RED
//
//  What the table adds on top of the router is the part a router cannot know —
//  a summary, which credential opens the door, and what the answers mean. That is
//  prose, and prose is exactly what a generator should not invent.
//
//  `document()` is pure: a table in, a JSON string out, no app and no database. The
//  generated bytes are COMMITTED at `baas/openapi.json` and a test re-bakes and
//  compares them, the same standard `.recipe`, `collection.json` and `reference.crep`
//  are held to — so a change to the API shows up as a diff somebody reads.
// =============================================================================
#pragma once

#include <string>
#include <vector>

namespace web::openapi {

// The version of the `/v1` contract this document describes. It is not the server's
// build id: two servers built a month apart serve the same contract, and the number
// moves when the CONTRACT does.
inline constexpr const char* kApiVersion = "1.0.0";

// Where the generated document is committed, relative to the repo root, and where
// `--openapi` writes it.
inline constexpr const char* kSpecPath = "baas/openapi.json";

// Which credential opens a route. Named after the doors rather than the filters, so
// the spec reads the way a caller thinks: an api key identifies the GAME, a bearer
// token identifies the PLAYER, and the two secrets identify an operator and the
// platform respectively.
enum class Auth {
    None,          // no credential at all
    ApiKey,        // X-Api-Key                       (the project)
    ApiKeyUser,    // X-Api-Key + Authorization: Bearer (a signed-in player)
    ApiKeySecret,  // X-Api-Key + X-Secret-Key         (the project's operator)
    AdminSecret,   // X-Admin-Secret                   (the platform)
};

struct Reply {
    int         code;
    const char* what;
};

struct Op {
    const char*        method;   // "GET", "POST", "PUT", "PATCH", "DELETE"
    const char*        path;     // "/v1/saves/{slot}" — Drogon's pattern IS OpenAPI's
    const char*        tag;
    const char*        summary;
    Auth               auth;
    const char*        body;     // "" when the operation takes no request body
    std::vector<Reply> replies;
};

// Everything this API answers to. One table; see the header comment for the two
// tests that keep it honest.
const std::vector<Op>& spec();

// The document. Pure — no app, no database, deterministic bytes.
std::string document(const std::vector<Op>& ops, const std::string& version);

// "GET /v1/saves" for every route, sorted. `live` asks Drogon what it registered;
// `documented` asks the table. `test_baas_openapi` asserts they are equal.
std::vector<std::string> live_routes();
std::vector<std::string> documented_routes();

}  // namespace web::openapi
