// =============================================================================
//  tests/test_baas_sql_seam.cc  —  one dialect in the source, two on the wire
// =============================================================================
//  Chapter 141. Every statement in baas/ is written in SQLite's dialect and
//  `web::db::portable` turns it into whatever the live backend speaks. Two halves,
//  and both of them have to hold or the other is worthless:
//
//    1. the translation is RIGHT — checked as VALUES, with no database anywhere
//       near it, because the whole reason this slice exists is that the Postgres
//       path was described in a comment and never executed;
//    2. nothing BYPASSES it — checked by reading the source. `portable` is only the
//       one translation if `execSqlSync` is unreachable from anywhere else, and a
//       rule nobody counts is a rule this repository has already broken twice.
// =============================================================================
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

#include "baas/db/db.h"
#include "tests/baas_test_util.h"

static int g_failures = 0;
#define CHECK(cond)                                                      \
    do {                                                                 \
        if (!(cond)) {                                                   \
            std::printf("FAIL %s:%d:  %s\n", __FILE__, __LINE__, #cond); \
            ++g_failures;                                                \
        }                                                                \
    } while (0)

using web::db::Dialect;
using web::db::portable;

static void eq(const std::string& got, const std::string& want, int line) {
    if (got == want) return;
    std::printf("FAIL %s:%d:\n  want: %s\n  got:  %s\n", __FILE__, line, want.c_str(),
                got.c_str());
    ++g_failures;
}
#define EQ(got, want) eq((got), (want), __LINE__)

static const char* kNow = "to_char(now() at time zone 'utc','YYYY-MM-DD HH24:MI:SS')";

int main() {
    // ---- 1. the translation, as values -------------------------------------
    const Dialect lite = Dialect::Sqlite, pg = Dialect::Postgres;

    // Placeholders. SQLite keeps `?`; Postgres counts from 1, and counts each `?`
    // separately even when two of them bind the same value — Drogon binds by
    // POSITION, so $1 twice would be one argument short.
    EQ(portable("SELECT a FROM t WHERE x=? AND y=?", lite),
       "SELECT a FROM t WHERE x=? AND y=?");
    EQ(portable("SELECT a FROM t WHERE x=? AND y=?", pg),
       "SELECT a FROM t WHERE x=$1 AND y=$2");
    EQ(portable("INSERT INTO t(a,b,c) VALUES(?,?,?)", pg),
       "INSERT INTO t(a,b,c) VALUES($1,$2,$3)");
    EQ(portable("SELECT * FROM t ORDER BY id DESC LIMIT ?", pg),
       "SELECT * FROM t ORDER BY id DESC LIMIT $1");

    // Numbering is per STATEMENT, not per process: two calls both start at $1.
    EQ(portable("SELECT ?", pg), "SELECT $1");
    EQ(portable("SELECT ?", pg), "SELECT $1");

    // A '?' inside a quoted literal is DATA. So is the word CURRENT_TIMESTAMP.
    EQ(portable("INSERT INTO t VALUES('a?b', ?)", pg), "INSERT INTO t VALUES('a?b', $1)");
    EQ(portable("SELECT 'CURRENT_TIMESTAMP' , ?", pg), "SELECT 'CURRENT_TIMESTAMP' , $1");
    // ...including through a doubled quote, which does not end the literal.
    EQ(portable("SELECT 'it''s ? here', ?", pg), "SELECT 'it''s ? here', $1");
    // A double-quoted identifier is skipped for the same reason.
    EQ(portable("SELECT \"od?d\" FROM t WHERE x=?", pg), "SELECT \"od?d\" FROM t WHERE x=$1");

    // AUTOID — the token that exists because `INTEGER PRIMARY KEY` means
    // auto-increment in one of these databases and "a column that stays NULL" in the
    // other. Expanded on BOTH backends, so the DDL never carries either spelling.
    EQ(portable("CREATE TABLE t (\n  id AUTOID,\n  x TEXT\n)", lite),
       "CREATE TABLE t (\n  id INTEGER PRIMARY KEY,\n  x TEXT\n)");
    EQ(portable("CREATE TABLE t (\n  id AUTOID,\n  x TEXT\n)", pg),
       "CREATE TABLE t (\n  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,\n"
       "  x TEXT\n)");
    // ...and an explicit INTEGER PRIMARY KEY is left ALONE, because
    // schema_migrations.version is one and is NOT a surrogate — the version is given.
    EQ(portable("CREATE TABLE m (version INTEGER PRIMARY KEY, name TEXT)", pg),
       "CREATE TABLE m (version INTEGER PRIMARY KEY, name TEXT)");

    // CURRENT_TIMESTAMP. Every timestamp column in this schema is TEXT, and Postgres
    // will not put a timestamptz in one — so it becomes text, in SQLite's format.
    EQ(portable("UPDATE t SET at=CURRENT_TIMESTAMP WHERE id=?", lite),
       "UPDATE t SET at=CURRENT_TIMESTAMP WHERE id=?");
    EQ(portable("UPDATE t SET at=CURRENT_TIMESTAMP WHERE id=?", pg),
       std::string("UPDATE t SET at=") + kNow + " WHERE id=$1");
    // Both sides of a comparison, which is where live_events reads it.
    EQ(portable("SELECT 1 WHERE a <= CURRENT_TIMESTAMP AND b >= CURRENT_TIMESTAMP", pg),
       std::string("SELECT 1 WHERE a <= ") + kNow + " AND b >= " + kNow);

    // Whole words only. A column called `autoid_at` or `current_timestamp_utc` is a
    // column, not a token — a substring rewriter would have produced garbage that
    // still parsed in one place and not the other.
    EQ(portable("SELECT autoidx, my_autoid FROM t", pg), "SELECT autoidx, my_autoid FROM t");
    EQ(portable("SELECT current_timestamp_utc FROM t", pg), "SELECT current_timestamp_utc FROM t");

    // Empty in, empty out; and a statement with nothing to translate is untouched.
    EQ(portable("", pg), "");
    EQ(portable("SELECT 1", pg), "SELECT 1");

    // ---- 2. nothing bypasses it --------------------------------------------
    // `portable` is the ONE translation only while `execSqlSync` is unreachable from
    // anywhere else. db.h is where the seam is built, so it is the only file allowed
    // to say the word.
    int offenders = 0, scanned = 0;
    for (const auto& e : std::filesystem::recursive_directory_iterator(BAAS_SRC_DIR)) {
        if (!e.is_regular_file()) continue;
        const std::string path = e.path().string();
        const std::string ext  = e.path().extension().string();
        if (ext != ".cc" && ext != ".h") continue;
        if (e.path().filename() == "db.h") continue;   // the seam itself
        ++scanned;
        std::ifstream in(path);
        std::string   line;
        int           n = 0;
        while (std::getline(in, line)) {
            ++n;
            // Only code, not the prose about it: every mention in a comment here is a
            // comment ABOUT the seam, and a test that fails on documentation teaches
            // people to stop writing it.
            const auto code = line.substr(0, line.find("//"));
            if (code.find("->execSqlSync(") != std::string::npos ||
                code.find(".insertId(") != std::string::npos) {
                std::printf("FAIL bypasses the seam: %s:%d\n%s\n", path.c_str(), n,
                            line.c_str());
                ++offenders;
            }
        }
    }
    std::printf("  scanned %d source files under %s\n", scanned, BAAS_SRC_DIR);
    CHECK(scanned > 30);       // the walk found the tree, not an empty directory
    CHECK(offenders == 0);

    // ---- 3. insert_id actually returns the id it made -----------------------
    // The RETURNING clause only exists on the Postgres branch, which is exactly the
    // branch nothing had ever run. So this runs against whichever backend is live and
    // asserts the row it names is the row that came back.
    const std::string name = "test_baas_sql_seam.db";
    baastest::cleanup_db(name);
    auto db = web::db::make_db_client(baastest::db_url(name));
    web::db::set_client(db);
    web::db::run_migrations(db);

    const long long id = web::db::insert_id(
        db, "INSERT INTO projects(name, public_key, secret_key_hash) VALUES(?,?,?)",
        std::string("Seam"), std::string("pk_seam"), std::string("h"));
    CHECK(id > 0);
    const auto back = web::db::exec(db, "SELECT name FROM projects WHERE id=?", id);
    CHECK(back.size() == 1);
    if (back.size() == 1) CHECK(back[0]["name"].as<std::string>() == "Seam");

    // A second insert gets a DIFFERENT id — which is the half `INTEGER PRIMARY KEY`
    // silently fails at on Postgres, where it is a plain column with no default.
    const long long id2 = web::db::insert_id(
        db, "INSERT INTO projects(name, public_key, secret_key_hash) VALUES(?,?,?)",
        std::string("Seam2"), std::string("pk_seam2"), std::string("h"));
    CHECK(id2 > 0);
    CHECK(id2 != id);

    if (g_failures == 0) std::printf("baas_sql_seam: all tests passed\n");
    else                 std::printf("baas_sql_seam: %d FAILURE(S)\n", g_failures);
    return g_failures == 0 ? 0 : 1;
}
