// =============================================================================
//  baas/db/db.h  —  database access for the BaaS backend
// =============================================================================
//  Wraps Drogon's DbClient behind a tiny seam: a url→client factory, an
//  idempotent schema migration, a seed, and a process-wide accessor the
//  controllers use.
//
//  TWO BACKENDS, and the difference between them is not a detail (chapter 140).
//  SQLite is single-writer, so the pool is ONE connection and a transaction holds
//  the only handle there is — which silently made every read-then-write in this
//  codebase atomic. Postgres has a real pool, and the moment it does, two requests
//  can both read a balance before either writes one. The lock has to be asked for,
//  and `lock_clause()` is where it is asked.
//
//  ...and until chapter 141 that was the ONLY difference this file knew about, because
//  nothing had ever executed a statement against Postgres. The first one that did died
//  on its own syntax. So the seam is wider now: `portable()` is the one translation,
//  `exec()` is the one door every statement goes through, and `insert_id()` is the one
//  place a new row's id comes from. A query that reaches `execSqlSync` directly bypasses
//  all three, and `test_baas_sql_seam` goes red if one does.
// =============================================================================
#pragma once

#include <future>
#include <string>
#include <type_traits>
#include <utility>
#include <vector>

#include <drogon/orm/DbClient.h>

namespace web::db {

using drogon::orm::DbClientPtr;

// Which backend the process is talking to. Set by `make_db_client`, read by
// `lock_clause` — the ONE place SQL differs between them, so a query that needs a
// row lock is written once and says so.
enum class Dialect { Sqlite = 0, Postgres };

[[nodiscard]] Dialect dialect();

// The row-lock clause for a SELECT whose result is about to be written back.
//
//   " FOR UPDATE" on Postgres — the reader blocks any other transaction reading the
//                 same row for update until this one commits.
//   ""            on SQLite   — the pool is one connection, so a transaction already
//                 holds the only handle. Emitting FOR UPDATE there is not a no-op,
//                 it is a syntax error: SQLite has no such clause.
//
// A caller that forgets this is not obviously wrong on SQLite and quietly wrong on
// Postgres, which is why `test_baas_purchase` runs two buyers at once and why
// `test_baas_dialect` asserts the clause is empty for exactly one of the two.
[[nodiscard]] const char* lock_clause();

// ---------------------------------------------------------------------------
//  ONE dialect in the source, TWO on the wire
// ---------------------------------------------------------------------------
//  Every statement in baas/ is written in one dialect — SQLite's, because that is what
//  this backend has always run on — and `portable` turns it into whatever the live
//  backend actually speaks. There are exactly three rewrites, and each is a disagreement
//  that CANNOT be papered over at a call site:
//
//    ?                 →  $1, $2, …   Drogon does not do this. It is why the very first
//                                     statement this repository ever sent to Postgres
//                                     came back "syntax error at or near ,".
//    AUTOID            →  a surrogate key that fills itself in. SQLite spells that
//                         `INTEGER PRIMARY KEY` (the rowid alias, already an
//                         auto-increment); Postgres needs `GENERATED BY DEFAULT AS
//                         IDENTITY` said out loud, and a bare `INTEGER PRIMARY KEY`
//                         there is a column that stays NULL and a table that refuses
//                         its second row.
//    CURRENT_TIMESTAMP →  a UTC timestamp AS TEXT, in SQLite's own format. Every
//                         timestamp column in this schema is TEXT, and Postgres will not
//                         put a timestamptz in one — not as a DEFAULT, not in an UPDATE,
//                         and not on either side of a comparison.
//
//  AUTOID is a token rather than a pattern match on `INTEGER PRIMARY KEY` on purpose:
//  `schema_migrations.version` is an INTEGER PRIMARY KEY that is NOT a surrogate — the
//  version number is supplied — and a rewriter clever enough to guess would have been
//  wrong about exactly that one.
//
//  Text inside quotes is left alone: a '?' in a string literal is data, not a
//  placeholder. Pure and total, so `test_baas_portable` checks its VALUE with no
//  database anywhere near it.
[[nodiscard]] std::string portable(const std::string& sql, Dialect d);

namespace detail {

// A Postgres parameter, and why it is not simply forwarded.
//
// Drogon binds an integral parameter in BINARY — `sizeof(T)` raw bytes, network order,
// with no type OID. Postgres therefore infers the parameter's type from the column and
// then insists the payload be exactly that wide. Every id column in this schema is
// INTEGER (4 bytes) and every id in this code is a C++ `long` (8), so the first run
// against a real Postgres produced fifty-eight of:
//
//     ERROR:  incorrect binary data format in bind parameter 1
//
// The fix is not "make all the widths agree". That is a rule with no test, held across
// a hundred call sites, that fails at runtime on the one backend nobody develops on —
// which is the exact shape of the problem this whole slice exists to end.
//
// A TEXT parameter has no width. Postgres coerces an untyped literal to whatever the
// column is, so `int`, `long` and `long long` all arrive as the same thing and none of
// them can be the wrong size. SQLite is left alone: its binding is typed and correct,
// and text there would lean on column affinity for no reason.
template <typename T>
decltype(auto) pg_arg(T&& v) {
    using D = std::decay_t<T>;
    if constexpr (std::is_integral_v<D> && !std::is_same_v<D, char>)
        return std::to_string(v);
    else
        return std::forward<T>(v);
}

}  // namespace detail

// Execute one statement, translated. `conn` is a DbClientPtr or a TransactionPtr — both
// answer `->execSqlSync`, and the point of the template is that a caller does not have
// to know which one it is holding.
template <typename Conn, typename... Args>
drogon::orm::Result exec(const Conn& conn, const std::string& sql, Args&&... args) {
    if (dialect() == Dialect::Postgres)
        return conn->execSqlSync(   // raw-sql: this IS the seam
            portable(sql, Dialect::Postgres), detail::pg_arg(std::forward<Args>(args))...);
    return conn->execSqlSync(   // raw-sql: ...and so is this
        portable(sql, Dialect::Sqlite), std::forward<Args>(args)...);
}

// Create the row if it is not there yet, and say whether THIS call is the one that
// made it.
//
// `FOR UPDATE` cannot lock a row that does not exist. Chapter 140 closed the
// lost-update race for a row that was already there and left the FIRST write wide
// open: two concurrent grants of a player's first item both found nothing, both took
// the INSERT branch, and on a backend with a real pool the loser is a unique-constraint
// violation — a grant that vanished, or, before the transaction existed, a dead process.
// SQLite's pool of one hid it perfectly; eight threads on one purse found it against
// Postgres in a second and a quarter.
//
// So: materialise, then lock. `ON CONFLICT DO NOTHING` with the target omitted means
// "any conflict" in both SQLite (3.24+) and Postgres (9.5+), and the loser of the race
// blocks until the winner commits and then does nothing — which is exactly what the
// caller wants, because the locking read that follows will find the winner's row.
template <typename Conn, typename... Args>
bool ensure_row(const Conn& conn, const std::string& insert_sql, Args&&... args) {
    return exec(conn, insert_sql + " ON CONFLICT DO NOTHING",
                std::forward<Args>(args)...).affectedRows() > 0;
}

// INSERT, and hand back the id of the row it made.
//
// SQLite answers that from the connection afterwards (`insertId()`, the last rowid).
// Postgres has no such thing: the id must be asked for IN the statement. So the clause
// is appended here rather than typed into eight INSERTs — seven of which would have it
// and the eighth would silently return 0.
template <typename Conn, typename... Args>
long long insert_id(const Conn& conn, const std::string& sql, Args&&... args) {
    if (dialect() == Dialect::Postgres) {
        const drogon::orm::Result r =
            conn->execSqlSync(   // raw-sql: this IS the seam
                portable(sql + " RETURNING id", Dialect::Postgres),
                detail::pg_arg(std::forward<Args>(args))...);
        return r.empty() ? 0 : r[0]["id"].as<long long>();
    }
    const drogon::orm::Result r =
        conn->execSqlSync(   // raw-sql: this IS the seam
            portable(sql, Dialect::Sqlite), std::forward<Args>(args)...);
    return static_cast<long long>(r.insertId());   // raw-sql: and this is the other half
}

// ---------------------------------------------------------------------------
//  A transaction that has actually COMMITTED by the time it goes out of scope
// ---------------------------------------------------------------------------
//  Drogon commits a transaction in its destructor, and the COMMIT is ENQUEUED on that
//  connection's event loop rather than executed there and then. With a pool of one that
//  is invisible: whatever the caller does next queues behind the commit on the same
//  connection, so it always sees it. With a real pool the next statement takes a
//  DIFFERENT connection and reads the state from before the commit.
//
//  That is what the first clean Postgres run actually looked like — no SQL errors left,
//  and the wrong number everywhere. `grant` returned 8 and the GET immediately after it
//  returned 7; forty-eight grants of one produced forty-seven. Not a lost update: a
//  write that had not landed yet. It is the third thing the pool of one was silently
//  providing, after atomicity (chapter 140) and the row that a lock could hold
//  (materialise-then-lock, above): read-your-own-writes.
//
//  So this waits. A mutating request must not answer before its commit is real, or the
//  GET that follows it is entitled to be older than the POST it followed.
class Transaction {
  public:
    explicit Transaction(const DbClientPtr& db);
    ~Transaction();

    Transaction(const Transaction&)            = delete;
    Transaction& operator=(const Transaction&) = delete;

    // Roll back, and do NOT wait afterwards: the caller is on an error path, is
    // returning a failure, and has nothing to read back. It also means this class never
    // depends on whether Drogon fires the commit callback for a rollback — the question
    // that would otherwise turn a wrong guess into a hung test suite.
    void rollback();

    // Both of these exist so a call site reads exactly as it did before: `db::exec(tx,
    // …)` finds `operator->`, and a helper taking the shared_ptr finds the conversion.
    drogon::orm::Transaction* operator->() const { return tx_.get(); }
    operator const std::shared_ptr<drogon::orm::Transaction>&() const { return tx_; }

  private:
    std::shared_ptr<drogon::orm::Transaction> tx_;
    std::future<bool>                         done_;
    bool                                      rolled_back_ = false;
};

// Build a DbClient from a url:
//   "sqlite://PATH"     — single connection; SQLite is single-writer
//   "postgres://..."    — needs a Drogon build with libpq (the Homebrew bottle has
//                         none; the drogonframework/drogon image does)
// `pool` is the connection count and is IGNORED for SQLite: more than one writer
// there means "database is locked", not more throughput.
// Throws std::runtime_error on an unsupported scheme.
DbClientPtr make_db_client(const std::string& url, int pool = 4);

// Apply every schema migration this DB is behind on, in version order, recording
// each in `schema_migrations`. Idempotent — safe to run every boot, and safe on a
// database created before the versioned engine existed (migration 1 is the original
// CREATE TABLE IF NOT EXISTS schema, so it just re-records as applied).
void run_migrations(const DbClientPtr& db);

// One applied schema migration (a row of schema_migrations). Exposed so tests and
// the backup/restore drill can answer "which schema version is this DB at?".
struct MigrationRecord {
    int         version;
    std::string name;
    std::string applied_at;
};
std::vector<MigrationRecord> applied_migrations(const DbClientPtr& db);

// Insert the demo project + its `colony_high` leaderboard if absent.
// Returns the project's public_key (existing or newly inserted).
std::string seed(const DbClientPtr& db);

// Process-wide accessor for the single application DbClient, set once at startup.
// (A single shared client is the whole app's DB handle; controllers read it here
//  rather than threading it through Drogon's framework-constructed objects.)
void        set_client(const DbClientPtr& db);
DbClientPtr client();

}  // namespace web::db
