// =============================================================================
//  baas/db/db.h  —  database access for the BaaS backend
// =============================================================================
//  Wraps Drogon's DbClient behind a tiny seam: a url→client factory, an
//  idempotent schema migration, a seed, and a process-wide accessor the
//  controllers use.
//
//  TWO BACKENDS, and the difference between them is not a detail (chapter 140).
//  SQLite is single-writer, so the pool is ONE connection and a transaction holds
//  the only handle there is — which silently made every read-then-write in this
//  codebase atomic. Postgres has a real pool, and the moment it does, two requests
//  can both read a balance before either writes one. The lock has to be asked for,
//  and `lock_clause()` is where it is asked.
//
//  ...and until chapter 141 that was the ONLY difference this file knew about, because
//  nothing had ever executed a statement against Postgres. The first one that did died
//  on its own syntax. So the seam is wider now: `portable()` is the one translation,
//  `exec()` is the one door every statement goes through, and `insert_id()` is the one
//  place a new row's id comes from. A query that reaches `execSqlSync` directly bypasses
//  all three, and `test_baas_sql_seam` goes red if one does.
// =============================================================================
#pragma once

#include <string>
#include <utility>
#include <vector>

#include <drogon/orm/DbClient.h>

namespace web::db {

using drogon::orm::DbClientPtr;

// Which backend the process is talking to. Set by `make_db_client`, read by
// `lock_clause` — the ONE place SQL differs between them, so a query that needs a
// row lock is written once and says so.
enum class Dialect { Sqlite = 0, Postgres };

[[nodiscard]] Dialect dialect();

// The row-lock clause for a SELECT whose result is about to be written back.
//
//   " FOR UPDATE" on Postgres — the reader blocks any other transaction reading the
//                 same row for update until this one commits.
//   ""            on SQLite   — the pool is one connection, so a transaction already
//                 holds the only handle. Emitting FOR UPDATE there is not a no-op,
//                 it is a syntax error: SQLite has no such clause.
//
// A caller that forgets this is not obviously wrong on SQLite and quietly wrong on
// Postgres, which is why `test_baas_purchase` runs two buyers at once and why
// `test_baas_dialect` asserts the clause is empty for exactly one of the two.
[[nodiscard]] const char* lock_clause();

// ---------------------------------------------------------------------------
//  ONE dialect in the source, TWO on the wire
// ---------------------------------------------------------------------------
//  Every statement in baas/ is written in one dialect — SQLite's, because that is what
//  this backend has always run on — and `portable` turns it into whatever the live
//  backend actually speaks. There are exactly three rewrites, and each is a disagreement
//  that CANNOT be papered over at a call site:
//
//    ?                 →  $1, $2, …   Drogon does not do this. It is why the very first
//                                     statement this repository ever sent to Postgres
//                                     came back "syntax error at or near ,".
//    AUTOID            →  a surrogate key that fills itself in. SQLite spells that
//                         `INTEGER PRIMARY KEY` (the rowid alias, already an
//                         auto-increment); Postgres needs `GENERATED BY DEFAULT AS
//                         IDENTITY` said out loud, and a bare `INTEGER PRIMARY KEY`
//                         there is a column that stays NULL and a table that refuses
//                         its second row.
//    CURRENT_TIMESTAMP →  a UTC timestamp AS TEXT, in SQLite's own format. Every
//                         timestamp column in this schema is TEXT, and Postgres will not
//                         put a timestamptz in one — not as a DEFAULT, not in an UPDATE,
//                         and not on either side of a comparison.
//
//  AUTOID is a token rather than a pattern match on `INTEGER PRIMARY KEY` on purpose:
//  `schema_migrations.version` is an INTEGER PRIMARY KEY that is NOT a surrogate — the
//  version number is supplied — and a rewriter clever enough to guess would have been
//  wrong about exactly that one.
//
//  Text inside quotes is left alone: a '?' in a string literal is data, not a
//  placeholder. Pure and total, so `test_baas_portable` checks its VALUE with no
//  database anywhere near it.
[[nodiscard]] std::string portable(const std::string& sql, Dialect d);

// Execute one statement, translated. `conn` is a DbClientPtr or a TransactionPtr — both
// answer `->execSqlSync`, and the point of the template is that a caller does not have
// to know which one it is holding.
template <typename Conn, typename... Args>
drogon::orm::Result exec(const Conn& conn, const std::string& sql, Args&&... args) {
    return conn->execSqlSync(portable(sql, dialect()), std::forward<Args>(args)...);
}

// INSERT, and hand back the id of the row it made.
//
// SQLite answers that from the connection afterwards (`insertId()`, the last rowid).
// Postgres has no such thing: the id must be asked for IN the statement. So the clause
// is appended here rather than typed into eight INSERTs — seven of which would have it
// and the eighth would silently return 0.
template <typename Conn, typename... Args>
long long insert_id(const Conn& conn, const std::string& sql, Args&&... args) {
    if (dialect() == Dialect::Postgres) {
        const drogon::orm::Result r =
            conn->execSqlSync(portable(sql + " RETURNING id", Dialect::Postgres),
                              std::forward<Args>(args)...);
        return r.empty() ? 0 : r[0]["id"].as<long long>();
    }
    const drogon::orm::Result r =
        conn->execSqlSync(portable(sql, Dialect::Sqlite), std::forward<Args>(args)...);
    return static_cast<long long>(r.insertId());
}

// Build a DbClient from a url:
//   "sqlite://PATH"     — single connection; SQLite is single-writer
//   "postgres://..."    — needs a Drogon build with libpq (the Homebrew bottle has
//                         none; the drogonframework/drogon image does)
// `pool` is the connection count and is IGNORED for SQLite: more than one writer
// there means "database is locked", not more throughput.
// Throws std::runtime_error on an unsupported scheme.
DbClientPtr make_db_client(const std::string& url, int pool = 4);

// Apply every schema migration this DB is behind on, in version order, recording
// each in `schema_migrations`. Idempotent — safe to run every boot, and safe on a
// database created before the versioned engine existed (migration 1 is the original
// CREATE TABLE IF NOT EXISTS schema, so it just re-records as applied).
void run_migrations(const DbClientPtr& db);

// One applied schema migration (a row of schema_migrations). Exposed so tests and
// the backup/restore drill can answer "which schema version is this DB at?".
struct MigrationRecord {
    int         version;
    std::string name;
    std::string applied_at;
};
std::vector<MigrationRecord> applied_migrations(const DbClientPtr& db);

// Insert the demo project + its `colony_high` leaderboard if absent.
// Returns the project's public_key (existing or newly inserted).
std::string seed(const DbClientPtr& db);

// Process-wide accessor for the single application DbClient, set once at startup.
// (A single shared client is the whole app's DB handle; controllers read it here
//  rather than threading it through Drogon's framework-constructed objects.)
void        set_client(const DbClientPtr& db);
DbClientPtr client();

}  // namespace web::db
